# Generated by Django 2.1.1 on 2019-01-20 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190120_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readnum',
            old_name='blg',
            new_name='blog',
        ),
    ]
